language: rust
rust:
  - stable
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    - llvm-toolchain-precise-3.6
    packages:
    - llvm-3.6
    - llvm-3.6-dev
    - libedit-dev
env:
  - LLVM_CONFIG="llvm-config-3.6"
script:
  - cargo test
  - cargo run --bin test-hubris
